### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by atif-zakaria** [brutalsavage/facebook-post-scraper#1]
hello i don't know why i'm getting this error 

Traceback (most recent call last):
  File "scraper.py", line 210, in <module>
    postBigDict = extract(page=args.page, numOfPost=args.len, infinite_scroll=infinite, scrape_comment=scrape_comment)
  File "scraper.py", line 178, in extract
    postBigDict = _extract_html(bs_data)
  File "scraper.py", line 48, in _extract_html
    commenter = comment.find(class_="_6qw4").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by brutalsavage** [comment]
Thanks, it should be fixed now
