### ISSUE TITLE
Comments return empty

### ISSUE THREAD

**Issue by ManuelBanza** [brutalsavage/facebook-post-scraper#15]
Hi @brutalsavage ,
I tried to download the comments from posts but it returns empty:
````
from scraper import extract
page = 'https://www.facebook.com/vodafonePT/'
comments = 'y'
list = extract(page, 30, comments)
````
and returns 'Comments': {} in every post. Did I miss something?

**### UPDATE:**

The comments field is returning data, however it only scrapes the most relevant comments. Any chance that it could scrap all coments instead @brutalsavage .

Thanks!

**Comment by ManuelBanza** [comment]
I came across this Expand All bookmark: http://com.hemiola.com/bookmarklet/
It works perfectly. Is it possible to incorporate that in the chromedriver before the scraping so it can scrape every single comment?
Cheers!

**Comment by brutalsavage** [comment]
Yeah right now the comments are not working correctly. Unfortunetly I don't have time this summer do a lot of work on this repo. If you want, you can create a pull request implementing this and I'll take a look

**Comment by gonhonoria** [comment]
@ManuelBanza  @brutalsavage i face the same issue... empty comments. How to deal with?
Also is there a specific tag for posts with special mention(looking for recommendations)

**Comment by rexshijaku** [comment]
@ManuelBanza @gonhonoria  is the account that you are using in English? if not can you try to change its language to English and try again? I found out that the issue which was causing problem to me was the language, since there was a bug in script. I made a pull request for the necessary changes that I think should be implemented. Hopefully this helps!

**Comment by gonhonoria** [comment]
Ooooh OK. I see then. For me the account is French. I will try your
suggestion and let you know. Thanks for the feedback.

**Comment by husseinYY** [comment]
We are waiting for the owner @brutalsavage  to accept the pull request that was made by @rexshijaku  

But if you know python you can certainly solve the problem yourself... Take a look at this

https://github.com/brutalsavage/facebook-post-scraper/pull/28/files

**Comment by brutalsavage** [comment]
Merged the pull request. Should fix the empty comment due to different language
