### ISSUE TITLE
could not convert string to float: '1,1'

### ISSUE THREAD

**Issue by atif-zakaria** [brutalsavage/facebook-post-scraper#2]
sorry for the disturb, i tried to solve it but i don't know the reason why 
Traceback (most recent call last):
  File "scraper.py", line 214, in <module>
    postBigDict = extract(page=args.page, numOfPost=args.len, infinite_scroll=infinite, scrape_comment=scrape_comment)
  File "scraper.py", line 182, in extract
    postBigDict = _extract_html(bs_data)
  File "scraper.py", line 88, in _extract_html
    realNum = float(num)
ValueError: could not convert string to float: '1,1'

**Comment by brutalsavage** [comment]
I'm not sure why that is happening, but i put in a replace in place for that so it should be fine now
