### ISSUE TITLE
Comments = 0

### ISSUE THREAD

**Issue by dosansil** [brutalsavage/facebook-post-scraper#3]
53             postDict['Comments'][commenter] = dict()
     54 
---> 55             comment_text = comment.find("span", class_="_3l3x").text
     56             postDict['Comments'][commenter]["text"] = comment_text
     57 

AttributeError: 'NoneType' object has no attribute 'text'

**Comment by brutalsavage** [comment]
should be fixed now, let me know if there is still a bug
