### ISSUE TITLE
uncollapsed comments and unfiltered comments

### ISSUE THREAD

**Issue by rexshijaku** [brutalsavage/facebook-post-scraper#30]
Opening this issue to mention two points which will be committed as solutions aftermath :

1. Facebook collapses comments, and they should be expanded (uncollapsed) before the view more comments can be generated (or before ranking them).
2. Comments  are usually filtered (ranked as e.g 'Most relevant comments') this doesn't mean that by clicking view more you can reach all comments! You should first filter them as 'All comments' and then try to view them.

**Comment by brutalsavage** [comment]
Good point and thanks for the fix
