### ISSUE TITLE
Went to an invalid post page

### ISSUE THREAD

**Issue by lt-shy-john** [brutalsavage/facebook-post-scraper#4]
When I used this scraper, the chromedriver lead me to the URL with this format `facebook.com/facebook.user/post`. The page says it is an invalid page. Did I commit something wrong in the argument lines?

**Comment by brutalsavage** [comment]
Right now the scraper can only scrape public page posts, I think you were trying to look at an user post and currently that is not available

**Comment by lt-shy-john** [comment]
> Right now the scraper can only scrape public page posts, I think you were trying to look at an user post and currently that is not available

Yes true. I just realised that last night and was hoping to tell you soon. I have successfully tried on a public page, so it should be fine now.

**Comment by lt-shy-john** [comment]
I mean this issue can be closed. Thanks, Steve!

**Comment by brutalsavage** [comment]
no probs
