### ISSUE TITLE
extract function returns empty list

### ISSUE THREAD

**Issue by futur3gho5t** [brutalsavage/facebook-post-scraper#40]
list = extract(page='https://www.facebook.com/bringmethehorizon', numOfPost=15, infinite_scroll=True, scrape_comment=True)
print("DONE!")
for i in list:
print(i)

returns nothing

**Comment by futur3gho5t** [comment]
list = extract(page=PAGE, numOfPost=15, infinite_scroll=True, scrape_comment=True)
print("DONE!")
for i in list:
    print(i)


returns nothing

**Comment by flavio2018** [comment]
Hi! Did you manage to solve the issue somehow?

**Comment by Wanthouser1** [comment]
I am having this issue as well

**Comment by mukurgupta** [comment]
Hi @futur3gho5t did you find a fix?
