### ISSUE TITLE
Timestamp and VIdeo Link

### ISSUE THREAD

**Issue by sebastienkanj** [brutalsavage/facebook-post-scraper#5]
Hi! If you want to add the Date the post was write and the link to a video upload to the facebook page you can add the following lines to the scraper.py file. 

       # Post Date
        postDate = item.find(class_="_5ptz")
        postDict['Date'] = postDate.get('data-utime')

        # Post Videos
        postVideos = item.find(class_="async_saving _400z _2-40 _5pcq")
        postDict['Video'] = ""
        if postVideos is not None:
                postDict['Video'] = "https://facebook.com"+postVideos.get('href')

**Comment by brutalsavage** [comment]
If you want you can make a pull request and ill add it in

**Comment by sebastienkanj** [comment]
Is my first time working in community in Github and I'm not sure that I do it well... Let me know if I fail in my try.

https://github.com/sebastienkanj/facebook-post-scraper/pull/1
