### ISSUE TITLE
The scraper doesn't work

### ISSUE THREAD

**Issue by busattoale** [brutalsavage/facebook-post-scraper#7]
command: python scraper.py  -p [page name] -l 18 -c y

Error 1:  in #reaction row 100

<img width="566" alt="Schermata 2020-03-07 alle 16 24 18" src="https://user-images.githubusercontent.com/25851699/76146127-99327780-6090-11ea-9181-23fd6d3ca2bc.png">

Error 2: If i comment the #reaction block and remove the column reaction from the output file, this is the result:

<img width="1150" alt="Schermata 2020-03-07 alle 16 37 18" src="https://user-images.githubusercontent.com/25851699/76146316-eebb5400-6091-11ea-97b3-1c09bafd008f.png">

<img width="46" alt="Schermata 2020-03-07 alle 16 38 54" src="https://user-images.githubusercontent.com/25851699/76146348-30e49580-6092-11ea-8c15-f0e993ebcb73.png">

As you can see the Comments column contains only {}.

**Comment by busattoale** [comment]
Solved comment but not reaction issues

**Comment by SirineZmantar** [comment]
hello how do you solved comment problem ?
